# Generated by Django 5.2.3 on 2025-06-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('character', models.CharField(default=None, max_length=60, null=True)),
                ('composer', models.CharField(default=None, max_length=60, null=True)),
                ('genre', models.CharField(default=None, max_length=60, null=True)),
                ('original_key', models.CharField(default=None, max_length=10, null=True)),
                ('show', models.CharField(default=None, max_length=60, null=True)),
            ],
        ),
    ]
