# Generated by Django 5.2.3 on 2025-06-25 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='original_key',
        ),
        migrations.AddField(
            model_name='arrangement',
            name='key',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='original_key',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.song'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='transposed',
            field=models.IntegerField(default=0),
        ),
    ]
