# Generated by Django 5.2.3 on 2025-06-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_song_original_key_arrangement_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyricist',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
