"""empty message

Revision ID: 9e163c83af4e
Revises: dd869f95935b
Create Date: 2025-06-13 17:43:49.303114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e163c83af4e'
down_revision = 'dd869f95935b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transposed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('transposed')
        batch_op.drop_column('original_key')

    # ### end Alembic commands ###
